### ISSUE TITLE
Export fails

### ISSUE THREAD

**Issue by Ethan1983** [ChristianBecker/inkscape-android-export#12]
Hello,
   Thanks for the extension. However, my export is failing in macOS with this error. Are there any other setup instructions?

Traceback (most recent call last):
  File "android_export.py", line 185, in <module>
    if options.optimize and not checkForPath("optipng"):
  File "android_export.py", line 35, in checkForPath
    ], stdout=DEVNULL, stderr=subprocess.STDOUT)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by Ethan1983** [comment]
This patch fixes it for me.

https://github.com/ChristianBecker/inkscape-android-export/pull/8
