### ISSUE TITLE
If optipng and imagemagick aren't installed, then an obscure error message is given

### ISSUE THREAD

**Issue by jwir3** [ChristianBecker/inkscape-android-export#6]
I'm using Mac OSX El Capitan. If neither ImageMagick nor OptiPNG are installed, and one of these checkboxes is selected when attempting to export, a subprocess python exception is given. This is pretty obscure, and took me a while to figure out what was wrong.

In the ideal case, an installation script for this plugin should be available which would automatically install whichever the user selected. In lieu of this, though, it would be better if the error message was a little clearer.

**Comment by ciani** [comment]
Hi there, 

This continue happen on Windows version, if you mark optipng or imagemagic and they are not  installed, the extension shows the following error:

Traceback (most recent call last):
  File "android_export.py", line 185, in <module>
    if options.optimize and not checkForPath("optipng"):
  File "android_export.py", line 35, in checkForPath
    ], stdout=DEVNULL, stderr=subprocess.STDOUT)
  File "C:\Program Files\Inkscape\python\Lib\subprocess.py", line 480, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Program Files\Inkscape\python\Lib\subprocess.py", line 633, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\python\Lib\subprocess.py", line 842, in _execute_child
    startupinfo)
WindowsError: [Error 2] El sistema no puede encontrar el archivo especificado

Thanks for your extension
